//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1_Mihailova_telecom2_projectApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public int ID { get; set; }
        public string NumberSubscriber { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int PaulId { get; set; }
        public System.DateTime DataBirthday { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public string ResidenceAddress { get; set; }
        public string FactAddress { get; set; }
        public string PassportSeriesAndNumber { get; set; }
        public string UnitCode { get; set; }
        public string IssuedByWhom { get; set; }
        public System.DateTime DateOfPassportIssue { get; set; }
        public string NumberContract { get; set; }
        public System.DateTime DateOfConclusionOfTheContract { get; set; }
        public int TypeContract { get; set; }
        public Nullable<int> ReasonForTerminationOfTheContract { get; set; }
        public string PersonalAccount { get; set; }
        public int Services { get; set; }
        public Nullable<System.DateTime> DateOfTerminationOfTheContract { get; set; }
        public int SerialNumberOfTheEquipment { get; set; }
    
        public virtual Paul Paul { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual SerialNumber SerialNumber { get; set; }
        public virtual Services Services1 { get; set; }
        public virtual TypeOfContract TypeOfContract { get; set; }
    }
}
