//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1_Mihailova_telecom2_projectApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public int IDRole { get; set; }
        public string Password { get; set; }
        public string Number { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
